love_record/urls.py
"""
name: urls.py
create_time: 2023-02-16
author: Ethan White

Description:
"""
from django.urls import path
from love_record import views

app_name = 'love_record'

urlpatterns = [
    path('', views.index, name='index'),
    # 故事相关的 url
    path('our_story/', views.our_story, name='our_story'),
    path('our_story/<int:story_id>/', views.story_detail, name='story_detail'),
    path('our_story/<int:story_id>/add_edit/', views.add_edit_story, name='add_edit_story'),
]

love_space/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('love_record.urls', namespace='love_record')),
    path('mdeditor/', include('mdeditor.urls')),
]


# static(如果符合这样规律的url，就去这个目录中找文件)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

love_record/models.py
import datetime
from django.db import models
from mdeditor.fields import MDTextField


# Create your models here.
class BaseModel(models.Model):
    visible = models.BooleanField(default=True, verbose_name='是否公开')

    class Meta:
        abstract = True


class User(models.Model):
    BOYFRIEND = 'boyfriend'
    GIRLFRIEND = 'girlfriend'
    OTHER = 'other'
    TAG = [
        (BOYFRIEND, '男朋友'),
        (GIRLFRIEND, '女朋友'),
        (OTHER, '其他'),
    ]
    username = models.CharField(max_length=32, verbose_name='用户名')
    password = models.CharField(max_length=128, verbose_name='用户密码')
    tag = models.CharField(max_length=16, choices=TAG, default=OTHER, verbose_name='用户标签')
    profile_img = models.ImageField(upload_to='user_img/', blank=True, verbose_name='用户头像')
    qq_id = models.CharField(blank=True, null=True, max_length=10, verbose_name='用户QQ号')
    phone = models.CharField(blank=True, null=True, max_length=16, verbose_name='用户手机号')
    wechat = models.CharField(blank=True, null=True, max_length=32, verbose_name='用户微信')
    birthday = models.DateField(blank=True, null=True, verbose_name='用户生日')
    location = models.CharField(blank=True, null=True, max_length=256, verbose_name='用户地址')
    remark = models.TextField(blank=True, null=True, verbose_name='用户简介')

    def __str__(self):
        return self.username

    class Meta:
        db_table = 'user'


class ChatRecord(BaseModel):
    chat_time = models.DateTimeField(verbose_name='聊天时间')
    sender = models.CharField(max_length=10, verbose_name='聊天对象')
    replay = models.BooleanField(default=False, verbose_name='是否为回复')
    content = models.TextField(blank=True, null=True, verbose_name='聊天内容')
    chat_img = models.ImageField(upload_to='chat_image/%Y/%m', name='', verbose_name='聊天图片')

    def __str__(self):
        return self.sender + self.chat_time.isoformat()

    class Meta:
        db_table = 'chat_record'
        ordering = ['-id']
        index_together = ['sender', 'chat_time']


class OurStory(BaseModel):
    story_title = models.CharField(max_length=128, verbose_name='故事标题')
    story_time = models.DateTimeField(db_index=True, verbose_name='故事时间')
    story_img = models.ImageField(upload_to='story_image/%Y/%m', verbose_name='故事图片')
    content = MDTextField()

    def __str__(self):
        return self.story_title

    class Meta:
        db_table = 'our_story'


class OurBlog(BaseModel):
    blog_time = models.DateTimeField(db_index=True, auto_now_add=True, verbose_name='blog 时间')
    blog_img = models.ImageField(upload_to='blog_image/%Y/%m', name='', verbose_name='blog 封面')
    content = MDTextField()

    def __str__(self):
        return f"Blog-{self.blog_time.date().isoformat()}"

    class Meta:
        db_table = 'out_blog'
        ordering = ['-id']


class OurGallery(BaseModel):
    img_time = models.DateTimeField(db_index=True, auto_now_add=True, verbose_name='图片上传时间')
    img = models.ImageField(upload_to='gallery/%Y/%m', name='', verbose_name='图片')
    img_info = models.TextField(blank=True, null=True, verbose_name='图片简介')

    def __str__(self):
        return f"img-{self.img_time.isoformat()}"

    class Meta:
        db_table = 'our_gallery'
        ordering = ['-id']


class LeaveBlessing(BaseModel):
    blessing_time = models.DateTimeField(db_index=True, auto_now_add=True, verbose_name='留言时间')
    writer = models.CharField(max_length=32, verbose_name='留言者')
    qq_id = models.CharField(max_length=10, blank=True, null=True, verbose_name='留言者QQ号码')
    email = models.EmailField(max_length=64, blank=True, null=True, verbose_name='用户邮箱')

    def __str__(self):
        return f"Img-{self.blessing_time.isoformat()}"

    class Meta:
        db_table = 'blessing'
        ordering = ['-id']

love_record/views.py
import markdown
import datetime
from django.shortcuts import render, get_object_or_404, redirect
from love_space.settings import BASE_DIR
from love_record.models import User, OurStory, OurGallery
from love_record.form import OurStoryForm


# Create your views here.
# TODO Our Story 我们的故事，用时间线，故事内容，图片来展示（markdown）
# TODO Our Blog 我们的博客，主要用于记录一些东西
# TODO Gallery 用于上传我们的相册
# TODO wedding even 婚礼事件（结婚还早）显示日期和地点
# TODO RSVP 用于用户留言（关键字屏蔽）

# TODO 编辑内容，每个字段显示是否公开，如果不公开，那么只有登录才能显示


def index(request):
    """主页"""
    # 定义遇见和在一起的时间
    met_list = [2022, 10, 27, 19, 26]  # JavaScript 上面月份是 0 - 11
    together_list = [2023, 1, 17, 20, 15]
    # 定义相遇时间
    met_time = datetime.datetime(2022, 11, 27, 19, 26)
    boyfriend = User.objects.filter(tag=User.BOYFRIEND).first()
    girlfriend = User.objects.filter(tag=User.GIRLFRIEND).first()
    met_year = met_time.strftime("%Y")
    met_month = met_time.strftime("%B")
    met_weekday = met_time.strftime("%A")
    met_day = met_time.strftime("%d")
    # 我们的相遇
    met_words = markdown.Markdown().convert(open(f'{BASE_DIR}/static/files/met_words.md').read())
    # 我们的故事
    stories = OurStory.objects.filter()[:4]
    # 我们的相册
    albums = OurGallery.objects.filter()[:8]
    return render(request, 'love_record/index.html', locals())


def our_story(request):
    """查看我们的故事"""
    stories = OurStory.objects.filter(visible=True)
    return render(request, 'love_record/story/our_story.html', locals())


def story_detail(request, story_id: int):
    """故事详情"""
    story = get_object_or_404(OurStory, id=story_id)
    story_content = markdown.Markdown().convert(story.content)
    return render(request, 'love_record/story/story_detail.html', locals())


# TODO 登录之后才能执行此操作
def add_edit_story(request, story_id):
    """添加或编辑故事"""
    content = "## 我们的故事"
    if story_id:
        story = OurStory.objects.filter(id=story_id).first()
        content = story.content
    # 如果提交方式为 POST，表示提交文案，后台保存
    if request.method == 'POST':
        form_data = request.POST
        visible = True if form_data.get('visible') == 'True' else False  # ['True']
        story_title = form_data.get('story_title')
        story_time = form_data.get('story_time')
        story_content = form_data.get('content')

        # 如果 id 不为 0，表示是编辑
        if story_id:
            story = OurStory.objects.get(id=story_id)
            story.story_title = story_title
            story.story_time = story_time
            story.content = story_content
        # id 为 0，表示是创建
        else:
            story = OurStory.objects.create(story_title=story_title,
                                            story_time=story_time,
                                            content=story_content)

        # 如果上传了图片
        if request.FILES:
            story.story_img = request.FILES['story-img']

        story.save()
        return redirect('love_record:story_detail', story_id)

    story_form = OurStoryForm(initial={'content': content})
    max_time = datetime.date.today()
    return render(request, 'love_record/story/story_form.html', locals())

templates/love_record/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="https://at.alicdn.com/t/c/font_3912375_om12gf7z9kr.css">
    {% block stylesheet %} {% endblock %}
    <script src="{% static 'js/header.js' %}" defer></script>
</head>
<body>
    <!--Header-->
    <header class="header">
        <div class="container">
            <div class="logo-container">
                <div class="header-logo">zh <span class="main-color">&amp;</span> mxh</div>
            </div>

            <div class="header-date d-none d-md-block">
                <p>Sunday, 27 <span class="main-color"> November </span> 2022 </p>
            </div>
            <div class="menu-toggle d-md-none d-sm-block float-end clearfix">
                <i class="iconfont icon-shouqicaidan text-white"></i>
            </div>
        </div>
    </header>
    <!--Header-->

    <!-- Site Navigation -->
    <nav class="mobile-nav d-md-none container-fluid d-sm-block position-fixed"
         style="left: 100vw;">
        <div class="row">
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    <a href="{% url 'love_record:index' %}">Home</a>
                </li>
                <li class="list-group-item">
                    <a href="{% url 'love_record:our_story' %}">Our Day</a>
                </li>
                <li class="list-group-item">
                    <a href="{% url 'love_record:our_story' %}">Our Story</a>
                </li>
                <li class="list-group-item">
                    <a href="#our-gallery">Gallery</a>
                </li>
                <li class="list-group-item">
                    <a href="#events">Wedding Events</a>
                </li>
                <li class="list-group-item">
                    <a href="#rsvp">RSVP</a>
                </li>
            </ul>
        </div>
    </nav>
    <nav class="navbar main-nav d-none d-md-flex">
        <div class="container">
            <ul class="nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'love_record:index' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'love_record:our_story' %}">Our Day</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'love_record:our_story' %}">Our Story</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#our-gallery">Gallery</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#events">Wedding Events</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#rsvp">RSVP</a>
                </li>
            </ul>
        </div>
    </nav>

{% block main %} {% endblock %}
{% block jsfile %} {% endblock %}
</body>
</html>

templates/love_record/our_gallery.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="css/bootstrap.css">
    <link rel="stylesheet" href="css/gallery.css">
</head>
<body>
    <div id="our-gallery" class="gallery container-fluid row">
        <div class="gallery-title text-center">
            <h1>Our Gallery</h1>
        </div>

        <div class="gallery-image col-lg-3 col-md-4 col-sm-6">
            <div class="item-caption"></div>
            <img src="http://img.netbian.com/file/2023/0223/232009Zt4AH.jpg" alt="">
        </div>
        <div class="gallery-image col-lg-3 col-md-4 col-sm-6">
            <div class="item-caption"></div>
            <img src="http://img.netbian.com/file/2023/0223/232009Zt4AH.jpg" alt="">
        </div>
        <div class="gallery-image col-lg-3 col-md-4 col-sm-6">
            <div class="item-caption"></div>
            <img src="http://img.netbian.com/file/2023/0223/232009Zt4AH.jpg" alt="">
        </div>
    </div>
</body>
</html>

templates/love_record/story/our_story.html
{% extends 'love_record/base.html' %}
{% load static %}

{% block stylesheet %}
    <link rel="stylesheet" href="{% static 'css/story/story.css' %}">
{% endblock %}

{% block main %}
<div class="our-stories container">
    <div class="story-title text-center">
        <h1>Our Story</h1>
    </div>
    <div class="stories">
        {% for story in stories %}
            <div class="card">
                <img class="card-img-top" src="{{ story.story_img.url }}" alt="">
                <div class="card-body">
                    <h3 class="card-title">{{ story.story_title }}</h3>
                    <div class="class-text">{{ story.content|truncatechars:100 }}</div>
                </div>
                <div class="card-footer">
                    <div class="text-muted">{{ story.story_time|date:"Y年m月d日" }}</div>
                    <a class="btn btn-info text-white" href="{% url 'love_record:story_detail' story.id %}">查看详情</a>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/love_record/story/story_detail.html
{% extends 'love_record/base.html' %}
{% load static %}

{% block stylesheet %}
    <link rel="stylesheet" href="{% static 'css/story/story_detail.css' %}">
{% endblock %}

{% block main %}
    <div class="story-card">
        <div class="detail-img">
            <img src="{{ story.story_img.url}}" alt="">
        </div>
        <div class="container row card-nav story-nav">
        <div class="card col-lg-2 d-none d-lg-flex">
            <div class="card-header">
                {{ story.story_title }}
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">在中间在中间在中间</li>
                <li class="list-group-item">在中间在中间在中间</li>
                <li class="list-group-item">在中间</li>
                <li class="list-group-item">在中间</li>
            </ul>
        </div>
        <div class="card col-lg-8 offset-lg-1">
            <div class="card-header text-center story-title">
                <h1 class="card-title">{{ story.story_title }}</h1>
                <a class="btn btn-info float-end text-white edit-btn" href="{% url 'love_record:add_edit_story' story.id %}">编辑文章</a>
            </div>
            <div class="card-body">
                {{ story_content|safe }}
            </div>
            <div class="card-footer text-end text-muted">
                {{ story.story_time|date:"Y年m月d日" }}
            </div>
        </div>
    </div>
    </div>
{% endblock %}

templates/love_record/story/story_form.html
{% extends 'love_record/base.html' %}
{% load static %}
{% block stylesheet %}
    <link rel="stylesheet" href="{% static 'css/bootstrap/fileinput.css' %}">
    <link rel="stylesheet" href="{% static 'css/story/story_form.css' %}">
{% endblock %}

{% block main %}
<div class="container story_form">
    <form class="row" action="" method="post" enctype="multipart/form-data"> <!--form这里一定要有 enctype="multipart/form-data" ，否则无法上传图片-->
        {% csrf_token %}
        <div class="basic col-lg-6 offset-lg-3">
            <div class="m-3">
                <input class="form-check-input" name="visible" type="checkbox" {% if story.visible %}checked{% endif %}  value='True' id="public">
                <label class="form-check-label" for="public">
                    是否公开
                </label>
            </div>
            <div class="input-group mb-3 story-title">
                <span class="input-group-text">故事标题</span>
                <input type="text" name="story_title" value="{{ story.story_title }}" maxlength="128" required class="form-control ps-4" placeholder="故事标题">
            </div>
            <div class="input-group mb-3 story-time">
                <label class="input-group-text">故事时间</label>
                <input type="datetime-local" name="story_time" value="{{ story.story_time|date:'Y-m-d\TH:i' }}" required min="2022-11-27T19:26" max="{{ max_time|date:'Y-m-d\T23:59' }}" class="form-control ps-4">
            </div>
            <div class="col-md-8 offset-md-2">
                <img class="img-fluid rounded" id="show-img"  src="{{ story.story_img.url }}" alt="">
            </div>
            <div class="input-group my-3">
                <input type="file" accept="image/*" name="story-img" id="story-img" value="{{ story.story_img }}" class="form-control">
                <button class="btn btn-outline-secondary px-4" type="button" id="img-btn">重置</button>
            </div>
        </div>
        <div class="content mb-5">
            {{ story_form.media }}
            {% for field in story_form %}
                <div class="input-group mb-3">
                    <label class="input-group-text">{{ field.label }}</label>
                    {{ field }}
                </div>
            {% endfor %}
            
        </div>
        <div>
            <input type="submit" class="btn btn-info float-end px-4 text-white mb-3">
        </div>
    </form>
</div>

{% endblock %}


{% block jsfile %}
<script>
    let show_img = document.querySelector('#show-img');
    let img_input = document.querySelector('#story-img');
    let img_btn = document.querySelector('#img-btn');
    const base_url = show_img.getAttribute('src')
    img_input.addEventListener('change', (e) => {
        const img = e.target.files[0];
        let reader = new FileReader();
        reader.onloadend = () => {
            console.log(reader.result)
            show_img.setAttribute('src', `${reader.result}`);
        }
        if (img){
            reader.readAsDataURL(img)
        }
    })
    img_btn.addEventListener('click', () => {
        show_img.setAttribute('src', base_url);
        img_input.value = '';
    })
</script>
{% endblock %}